repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v19.1.5'
    hooks:
      - id: clang-format
        exclude: ^3rdparty/

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.13.0
    hooks:
      - id: markdownlint-cli2
        exclude: "include/ur_client_library/queue/LICENSE.md"
  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v0.9.1
    hooks:
      - id: sphinx-lint
