name: ROS industrial ci
on: [push, pull_request]

jobs:
  format_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: 'ros-industrial/industrial_ci@master'
      env:
        ROS_DISTRO: melodic
        CLANG_FORMAT_CHECK: file
        CLANG_FORMAT_VERSION: "9"

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - ROS_DISTRO: melodic
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS_Driver#master https://raw.githubusercontent.com/UniversalRobots/Universal_Robots_ROS_Driver/master/.melodic.rosinstall"
            DOCKER_RUN_OPTS: --network ursim_net
            BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
            URSIM_VERSION: '5.5.1'
            ROBOT_MODEL: 'ur5e'
            PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
          - ROS_DISTRO: noetic
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS_Driver#master https://raw.githubusercontent.com/UniversalRobots/Universal_Robots_ROS_Driver/master/.noetic.rosinstall"
            BUILDER: catkin_tools
            DOCKER_RUN_OPTS: --network ursim_net
            BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
            URSIM_VERSION: '5.5.1'
            ROBOT_MODEL: 'ur5e'
            PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
          - ROS_DISTRO: foxy
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#foxy"
            DOCKER_RUN_OPTS: --network ursim_net
            BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
            URSIM_VERSION: '5.5.1'
            ROBOT_MODEL: 'ur5e'
            PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
            NOT_TEST_DOWNSTREAM: true
          - ROS_DISTRO: galactic
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#galactic"
            DOCKER_RUN_OPTS: --network ursim_net
            BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
            URSIM_VERSION: '5.5.1'
            ROBOT_MODEL: 'ur5e'
            PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
            NOT_TEST_DOWNSTREAM: true
          - ROS_DISTRO: humble
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#main https://raw.githubusercontent.com/UniversalRobots/Universal_Robots_ROS2_Driver/main/Universal_Robots_ROS2_Driver-not-released.humble.repos"
            DOCKER_RUN_OPTS: --network ursim_net
            BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
            URSIM_VERSION: '5.5.1'
            ROBOT_MODEL: 'ur5e'
            PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
            NOT_TEST_DOWNSTREAM: true
          - ROS_DISTRO: rolling
            ROS_REPO: main
            IMMEDIATE_TEST_OUTPUT: true
            DOWNSTREAM_WORKSPACE: "github:UniversalRobots/Universal_Robots_ROS2_Driver#main https://raw.githubusercontent.com/UniversalRobots/Universal_Robots_ROS2_Driver/main/Universal_Robots_ROS2_Driver-not-released.rolling.repos"
            DOCKER_RUN_OPTS: --network ursim_net
            BEFORE_INIT: 'apt-get update -qq && apt-get install -y iproute2 iputils-ping && ip addr && ping -c5 192.168.56.101'
            URSIM_VERSION: '5.5.1'
            ROBOT_MODEL: 'ur5e'
            PROGRAM_FOLDER: 'tests/resources/dockerursim/programs/e-series'
            NOT_TEST_DOWNSTREAM: true

    steps:
      - uses: actions/checkout@v1
      - name: start ursim
        run: |
          scripts/start_ursim.sh -m $ROBOT_MODEL -v $URSIM_VERSION -p $PROGRAM_FOLDER -d
        env: ${{matrix.env}}
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
